-- GestionCours schema for Supabase (PostgreSQL)
-- Apply via Supabase SQL editor or: supabase db push

create table if not exists public.filieres (
  id bigint generated by default as identity primary key,
  name text not null,
  level text not null,
  desktop_id integer unique,
  created_at timestamptz not null default now(),
  constraint uq_filiere_name_level unique (name, level)
);

create table if not exists public.teachers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  email text,
  created_at timestamptz not null default now()
);

create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  name text not null unique,
  capacity integer not null default 0,
  desktop_id integer unique,
  created_at timestamptz not null default now()
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  subject text not null unique,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  student_number text not null unique,
  first_name text not null,
  last_name text not null,
  email text not null unique,
  password_hash text not null,
  filiere_id bigint not null references public.filieres (id),
  level text not null,
  created_at timestamptz not null default now()
);

create index if not exists ix_students_filiere_id on public.students (filiere_id);

create table if not exists public.schedule (
  id bigint generated by default as identity primary key,
  desktop_id integer unique,
  filiere_id bigint not null references public.filieres (id),
  day text not null,
  start_time time not null,
  end_time time not null,
  subject text not null,
  teacher text not null,
  room text,
  group_tc text,
  week_date date not null,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint uq_schedule_slot unique (filiere_id, week_date, day, start_time, subject, group_tc)
);

create index if not exists ix_schedule_week_filiere on public.schedule (week_date, filiere_id);
create index if not exists ix_schedule_filiere_id on public.schedule (filiere_id);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students (id) on delete cascade,
  filiere_id bigint references public.filieres (id),
  title text not null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists ix_notifications_student_id on public.notifications (student_id);

-- Backend uses the service role key (bypasses RLS).
-- Anon access is denied by default; open read policies only if the SPA talks to Supabase directly.
alter table public.filieres enable row level security;
alter table public.teachers enable row level security;
alter table public.rooms enable row level security;
alter table public.courses enable row level security;
alter table public.students enable row level security;
alter table public.schedule enable row level security;
alter table public.notifications enable row level security;
